### ISSUE TITLE
Feature Request: A way to tell if a meme is banned without buying it. 

### ISSUE THREAD

**Issue by Blackhawkwentworth** [meme-exchange/server#14]
In using meme trades, often I'll buy a stock, only to see it banned after buying it. Is there a way of noting which stocks are banned before one buys?

**Comment by suBDavis** [comment]
So banning works like this.

If you already own a meme when it gets banned, you can sell what you have to get your money back but not buy more.

If you don't already own a banned meme, the only place you'll notice it is recent trades.

To check if a meme is banned, type or paste it into the search bar.  If it doesn't show up, it's banned!

Does this answer your question?

**Comment by QuadmasterXLII** [comment]
We could put the (**Banned) sign in recent trades

**Comment by Blackhawkwentworth** [comment]
Yeah, that would work! Thanks!
