### ISSUE TITLE
Highcharts

### ISSUE THREAD

**Issue by Dafondo** [meme-exchange/server#16]
http://jsfiddle.net/Dafondo/uLfpnafk/9/
Still looks a little too pretty for memetrades
Drag L-->R to zoom in, L<--R to zoom out, shift-drag to pan

Todo:
- [ ] better (ie. less better) colors
- [ ] de-goodify
- [ ] jpegify
- [ ] memeify

**Comment by suBDavis** [comment]
I actually like that a lot.  I'll see how hard it would be to merge into the current code tomorrow...

**Comment by suBDavis** [comment]
Rolled into production.  Good work!
