### ISSUE TITLE
Issue with user portfolio appraisal 

### ISSUE THREAD

**Issue by suBDavis** [meme-exchange/server#3]

**Comment by suBDavis** [comment]
Still isn't great but it works.

**Comment by suBDavis** [comment]
Where are we at here @QuadmasterXLII ?  Is cron running the update script?

**Comment by QuadmasterXLII** [comment]
It's run with the design pattern while true; sleep 60; python update.py; done in a screen session

**Comment by suBDavis** [comment]
done
